//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement_Model.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseManagement557Entities1 : DbContext
    {
        public CourseManagement557Entities1()
            : base("name=CourseManagement557Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Enrollment> Enrollment { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Submission> Submission { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Discussion> Discussion { get; set; }
    }
}
